# === Prezto ===
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# === Color scheme ===
BASE16_SCHEME="monokai"
if [[ -s "$HOME/dotfiles/base16-monokai.sh" ]]; then
    source "$HOME/dotfiles/base16-monokai.sh"
fi
unset BASE16_SCHEME

# === Capslock remap ===
if [[ `uname` == "Linux" ]] && type setxkbmap > /dev/null; then
    setxkbmap -layout us -option ctrl:nocaps
fi

# === Terminal ===
stty -ixon # disable flow control (CTRL-S, CTRL-Q)

# === Environment ===
export KEYTIMEOUT=1
export BB_NUMBER_THREADS="8"
export PARALLEL_MAKE="-j8"
export MAKEFLAGS="-j8"

# === Alias ===
alias sshi='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR'
alias scpi='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR'
alias n='e ~/work/notes/scratchpad.txt'

# === zsh key bindings ===
bindkey '^_' undo

# === tmux autostart ===
if [[ -z "$TMUX" && -z "$EMACS" && -z "$VIM" && \
    -z "$INSIDE_EMACS" && -z "$VSCODE_PID" && -z "$SSH_TTY" ]]
then
    tmux start-server
    tmux_session='zshrc'

    if ! tmux has-session -t "$tmux_session" 2> /dev/null; then
        tmux \
            new-session -d -s "$tmux_session" \; \
            set-option -t "$tmux_session" destroy-unattached off &> /dev/null
        # Restore saved session
        $HOME/dotfiles/tmux/plugins/resurrect/scripts/restore.sh 2> /dev/null
        # Attach to the new session
        exec tmux attach-session -d -t "$tmux_session"
    elif [[ -z `tmux list-clients -t $tmux_session` ]]; then
        # Attach to the existing session
        exec tmux attach-session -d -t "$tmux_session"
    fi
fi

# === Local config ===
if [[ -s "$HOME/.zshrc_local" ]]; then
    source "$HOME/.zshrc_local"
fi

source $HOME/dotfiles/zsh/functions/_tmux_pane_words.zsh
